# Numpy

# Basics, Array Creation, Indexing

[www.numpy.org](http://www.numpy.org)

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

In [1]:
import numpy as np

In [2]:
def iprint(seq, sep='--------'):
    for item in seq:
        print(item)
        print(sep)

In [3]:
np.__version__

'1.13.0'

### Fast and memory efficient 

In [2]:
L = range(1000)
%timeit [i**2 for i in L]

290 µs ± 2.22 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
a = np.arange(1000)
%timeit a**2

1.17 µs ± 25.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Numpy Reference documentation

In [98]:
#np.lookfor('create array')

In [99]:
#np.con*?

## Array Creation

In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.ndim

1

In [9]:
b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
print('Array:\n', b, '\n')
print('Number of dimensions:\t', b.ndim)
print('Shape:\t\t\t', b.shape)
print('Array size:\t\t', b.size)
print('Element type:\t\t', b.dtype)
print('Element memory size:\t', b.itemsize, '  (in bytes)')
print('Array memory size:\t', b.nbytes, ' (in bytes)')

Array:
 [[0 1 2]
 [3 4 5]] 

Number of dimensions:	 2
Shape:			 (2, 3)
Array size:		 6
Element type:		 int64
Element memory size:	 8   (in bytes)
Array memory size:	 48  (in bytes)


In [93]:
b = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]
              ]
            )
print('Array:\n', b, '\n')
print('Number of dimensions:\t', b.ndim)
print('Shape:\t\t\t', b.shape)
print('Array size:\t\t', b.size)

Array:
 [[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]] 

Number of dimensions:	 3
Shape:			 (2, 2, 3)
Array size:		 12


In [11]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))

List to array: 
[1 2 3 4 5 6 7 8]


In [12]:
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))

Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [34]:
x = np.arange(10, dtype=np.uint8)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [35]:
x.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
bs = x.tobytes()
bs

b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t'

In [37]:
np.fromstring(bs, dtype=np.uint8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [16]:
c = np.array([[0, 1, 2], [3, 4, 5]], dtype=np.int8)

In [38]:
c.itemsize

1

In [39]:
d = np.array( [ [1,2], [3,4] ], dtype=np.complex )

In [40]:
d

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [41]:
d.itemsize

16

In [42]:
o = np.array([1, 'abcd', None, 2.1])

In [43]:
o.itemsize

8

In [44]:
np.arange(1 , 9 , 2 ) # start, end (exclusive), step

array([1, 3, 5, 7])

In [45]:
np.arange( 0, 2, 0.3 ) # it accepts float arguments

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [46]:
# linearly spaced
np.linspace(0 , 1 , 6 ) # start, end, number of points

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [47]:
# logarithmically spaced
np.logspace(2 , 10 , 3 ) # start, end, number of points

array([  1.00000000e+02,   1.00000000e+06,   1.00000000e+10])

In [2]:
np.ones((3, 3)) # reminder: (3, 3) is a tuple

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [6]:
np.full((3,3),fill_value=3.14)
# np.ones((3,3))*3.14

array([[ 3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14]])

In [3]:
np.zeros((2, 2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [4]:
# creates an array whose initial content is random and depends on the state of the memory
np.empty((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.zeros_like(a) # np.zeros(a.shape)

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
np.ones_like(a) # np.ones(a.shape)

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
# identity array
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [13]:
np.eye(3, k=0)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
np.eye(3, k=1)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [52]:
np.diag(np.array([1 ,2 ,3 ,4 ]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [53]:
np.tri(3,4)

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.]])

In [54]:
np.tri(3,4, 0)

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.]])

In [55]:
np.tri(3,4,1)

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  1.,  1.]])

In [56]:
np.tri(3,4,-1)

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.]])

In [57]:
np.tri(3,4,-2)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.]])

In [58]:
np.tri?

In [59]:
np.triu(np.ones(3))

array([[ 1.,  1.,  1.],
       [ 0.,  1.,  1.],
       [ 0.,  0.,  1.]])

In [62]:
np.triu(np.ones(3),1)

array([[ 0.,  1.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [63]:
np.random.seed(1234)

In [64]:
np.random.rand(4) # uniform in [0, 1]

array([ 0.19151945,  0.62210877,  0.43772774,  0.78535858])

In [65]:
np.random.randn(4) # Gaussian

array([-0.72058873,  0.88716294,  0.85958841, -0.6365235 ])

In [66]:
np.random.randint(0 , 20, 10 )

array([12, 16,  5, 16,  9, 15, 18, 16, 12,  5])

In [389]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [390]:
np.random.shuffle(x)
x

array([7, 2, 3, 1, 6, 4, 0, 9, 8, 5])

#### Exercise
Create this 2D array.
```python
array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  9,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 15,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 18,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 21,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 24]])
```

In [70]:
np.diag(np.arange(0,27,3))

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  9,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 15,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 18,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 21,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 24]])

## Array data types

In [71]:
a = np.array([1 , 2 , 3 ])
a.dtype

dtype('int64')

In [72]:
b = np.array([ 0.1, 2., 3.6])
b.dtype

dtype('float64')

In [73]:
b.itemsize

8

In [74]:
x = b.astype(int)
x

array([0, 2, 3])

In [75]:
x.itemsize

8

In [76]:
x.dtype

dtype('int64')

In [77]:
x = b.astype(np.int8)

In [78]:
x.itemsize

1

In [79]:
c = np.array([1 , 2 , 3 ], dtype = float )
c.dtype

dtype('float64')

In [80]:
d = np.array([1 + 2j, 3 + 4j, 5 + 6 * 1j ])
d.dtype

dtype('complex128')

In [81]:
e = np.array([True, False , False , True])
e.dtype

dtype('bool')

In [82]:
e.itemsize

1

In [83]:
f = np.array(['Bonjour' , ' Hello' , ' Hallo' ,])
f.dtype # <--- strings containing max. 7 letters

dtype('<U7')

In [84]:
f.itemsize

28

In [85]:
g = np.array(['Bonjour Madam' ,'çğıöüş'])
g.dtype # <--- strings containing max. 21 letters

dtype('<U13')

In [86]:
g.itemsize

52

#### Exercise
Create an array ranging from 0 to 10 with 0.5 step size and then convert it to integer array.

In [87]:
np.arange(0, 10, 0.5).astype(np.uint8)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9], dtype=uint8)

## Shape Operations

In [88]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
x.shape

(12,)

In [90]:
x.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
x.shape

(12,)

In [92]:
x.reshape((6,-1))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [93]:
x.reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [94]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [95]:
x.resize((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
a = np.array([[1,2], [3,4]])
a.resize((4,1))
a

array([[1],
       [2],
       [3],
       [4]])

In [9]:
a = np.array([1,2,3])
np.resize(a, (2,4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2]])

In [98]:
row_vector = np.arange(6)
print(row_vector)
print(row_vector.ndim)
print(row_vector.shape)

[0 1 2 3 4 5]
1
(6,)


In [99]:
row_vector.T

array([0, 1, 2, 3, 4, 5])

In [122]:
row_vector[:]

array([0, 1, 2, 3, 4, 5])

In [123]:
row_vector[:,:]

IndexError: too many indices for array

In [89]:
a = np.array([[1, 2, 3], [3, 4, 5]])
b = a.flatten() # default: C order

In [29]:
print(a)
print()
print(b)

[[1 2 3]
 [3 4 5]]

[1 2 3 3 4 5]


In [14]:
a = np.array([[1, 2, 3], [3, 4, 5]])
b = a.flatten(order='F') # Fortran order

In [12]:
print(a)
print()
print(b)

[[1 2 3]
 [3 4 5]]

[1 3 2 4 3 5]


In [31]:
np.ravel(a)

array([1, 2, 3, 3, 4, 5])

In [32]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [119]:
row_array = row_vector[:, np.newaxis]
row_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [121]:
print(row_vector.shape)
print(row_array.shape)

(6,)
(6, 1)


In [112]:
column_array = np.arange(0, 51, 10).reshape((-1,1))
print(column_array)
print(column_array.ndim)
print(column_array.shape)

[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
2
(6, 1)


In [113]:
column_array.T

array([[ 0, 10, 20, 30, 40, 50]])

In [114]:
column_array.T.shape

(1, 6)

In [110]:
column_vector

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [115]:
column_array

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [116]:
np.arange(0, 51, 10)[:, np.newaxis]

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [8]:
np.arange(0, 51, 10)[np.newaxis, :]

array([[ 0, 10, 20, 30, 40, 50]])

In [118]:
# broadcasting
row_vector + column_array

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [90]:
x = np.random.rand(3, 4, 1)
y = np.squeeze(x)
print(x.shape)
print(y.shape)

(3, 4, 1)
(3, 4)


#### Exercise
Create the following 3x4 matrix.

Expected Output:
```python
array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])
``` 

In [131]:
np.arange(1,13).reshape((3,4))*3

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [130]:
np.arange(3,37,3).reshape((3,4))

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

#### Exercise
Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [ ]:
x = np.ones([10, 10, 3]).reshape(x, [-1, 150])

## Iteration
Iterating over multidimensional arrays is done with respect to the first axis.

In [224]:
a = np.arange(12).reshape(3,4)
for row in a:
    print(row)
    print("----------------")

[0 1 2 3]
----------------
[4 5 6 7]
----------------
[ 8  9 10 11]
----------------


In [309]:
for i,row in enumerate(a):
    print("row ",i)
    print("----------------")
    print(row)

row  0
----------------
4
row  1
----------------
3
row  2
----------------
1
row  3
----------------
2


In [227]:
a = np.arange(12).reshape(3,2,2)
a.shape

(3, 2, 2)

In [225]:
for element in a.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11


#### Exercise
Create a 5x5 zero array and with a number n given by user, change nth element of first row, n+1 element for the next row, so on. Return to beginning of the row it exceeds the row size.

Input:
```python
x = np.zeros((5,5))
n = 2
```

Expected output:
```python
array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.]])
```


In [318]:
x = np.zeros((5,5))
n = 2
for i,row in enumerate(x):
    x[i,(i+n)%5] = 1
x

array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.]])

## Indexing  Slicing

<img src='../img/numpy_array_slicing.png'>

In [132]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
a[2]

2

In [134]:
b = np.diag(np.arange(3))
b

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [135]:
b[1, 1]

1

In [136]:
a[0:4]

array([0, 1, 2, 3])

In [137]:
a[-4:-1]

array([6, 7, 8])

In [138]:
# reversed
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [139]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
a[2:9:3] # [start:end:step]

array([2, 5, 8])

In [141]:
a = np.arange(6) + np.arange(0,51,10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [142]:
a[0,3:5]

array([3, 4])

In [143]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [144]:
a[2:]

array([[20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [145]:
a[:,:2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51]])

In [146]:
slice?

In [147]:
slice(0,10,3)

slice(0, 10, 3)

In [148]:
np.arange(10)[slice(0,10,3)]

array([0, 3, 6, 9])

In [149]:
np.s_?

In [150]:
np.s_[0:10:3]

slice(0, 10, 3)

In [4]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a[1] = 11

In [6]:
a

array([ 0, 11,  2,  3,  4,  5,  6,  7,  8,  9])

In [7]:
a[2:5] = [22,33,44]

In [8]:
a

array([ 0, 11, 22, 33, 44,  5,  6,  7,  8,  9])

In [9]:
a[2:5] = np.array([-2,-3,-4])

In [10]:
a

array([ 0, 11, -2, -3, -4,  5,  6,  7,  8,  9])

In [11]:
# assignment does match the length of slice
a[6:9] = np.array([-6,-7])

ValueError: could not broadcast input array from shape (2) into shape (3)

In [12]:
a

array([ 0, 11, -2, -3, -4,  5,  6,  7,  8,  9])

In [13]:
# assignment does match the length of slice
a[6:9] = np.array([-6])

In [14]:
a

array([ 0, 11, -2, -3, -4,  5, -6, -6, -6,  9])

In [17]:
np.delete?

In [15]:
np.delete(a, [8,9])

array([ 0, 11, -2, -3, -4,  5, -6, -6])

In [163]:
a

array([ 0, 11, -2, -3, -4,  5, -6, -6, -6,  9])

In [164]:
np.delete(a, np.s_[0:3])

array([-3, -4,  5, -6, -6, -6,  9])

In [165]:
tda = np.arange(20).reshape((4,-1))
tda

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [166]:
np.delete(tda, (1,2), axis=0)

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [167]:
np.delete(tda, (1,2), axis=1)

array([[ 0,  3,  4],
       [ 5,  8,  9],
       [10, 13, 14],
       [15, 18, 19]])

#### Exercise
Write a Python program to create a 2d array with 1 on the border and 0 inside.

Original array: 
```
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)
```
Expected Output:
```
array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)
```

In [168]:
a = np.ones((5,5), dtype=np.uint8)
a[1:-1,1:-1]=0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

#### Exercise
Write a Python program to create a 2d array with 0 on the border and 1 inside.

Original array: 
```python
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8) 
```

Expected Output:
```python
array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)
```

In [169]:
a = np.ones((5,5), dtype=np.uint8)
a[0,:] = 0
a[-1,:] = 0
a[:,0] = 0
a[:,-1] = 0
a

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

#### Exercise
Write a Python program to pad a given 2D given array with 0.

Original array: 
```python
array([[ 4, 11,  9, 19],
       [ 8, 12,  0, 12],
       [ 7,  1, 16,  3]])
```

Expected Output:
```python
array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  4, 11,  9, 19,  0],
       [ 0,  8, 12,  0, 12,  0],
       [ 0,  7,  1, 16,  3,  0],
       [ 0,  0,  0,  0,  0,  0]])
```

In [170]:
a = np.random.randint(0,20,12).reshape((3,4))
nr, nc = a.shape
b = np.zeros((nr+2, nc+2))
b[1:-1,1:-1] = a

print(a)
print()
print(b.astype(np.uint8))

[[ 2  6  3  7]
 [11  0  9 11]
 [16  3  2 19]]

[[ 0  0  0  0  0  0]
 [ 0  2  6  3  7  0]
 [ 0 11  0  9 11  0]
 [ 0 16  3  2 19  0]
 [ 0  0  0  0  0  0]]


#### Exercise
Create the 2D array below by using reshape and delete operations.

```python
array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])
``` 

In [19]:
np.arange(60).reshape((6,-1))[:,:6]

In [20]:
a[:,:6]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [171]:
a = np.arange(60).reshape((6,-1))
b = np.delete(a, (6,7,8,9), axis=1)
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

#### Exercise
Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

Expected Output:
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [172]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=np.uint8)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Example

In [173]:
is_prime = np.ones((100, ))

In [174]:
is_prime[:2] = 0
is_prime

array([ 0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [175]:
N_max = int(np.sqrt(len(is_prime)))
for j in range(2,N_max):
    is_prime[j*j::j] = 0

In [176]:
is_prime

array([ 0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
        1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.])

In [177]:
np.nonzero(is_prime)

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
        61, 67, 71, 73, 79, 83, 89, 97]),)

### 3D Arrays

In [97]:
x = np.arange(24).reshape(2,3,4)
iprint(x, sep='-'*20)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------


In [202]:
x[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [203]:
x[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [204]:
x[0].shape

(3, 4)

In [208]:
# ellipsis operator
x[1,...] # same as x[1,:,:] or x[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [209]:
x[...,2] # same as x[:,:,2]

array([[  2,  13],
       [102, 113]])

In [205]:
x[0, 0:2, 2:] # 1s dim: 0th element, 2nd dim: from 0th to 2, 3rd dim: from 2nd to end 

array([[2, 3],
       [6, 7]])

### Fancy indexing

<img src='../img/numpy_fancy_indexing.png'>

In [178]:
a = np.arange(10)

In [179]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool)

In [180]:
mask = (a % 2 == 0)

In [181]:
mask

array([ True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool)

In [182]:
a[mask]

array([0, 2, 4, 6, 8])

In [183]:
a = np.arange(10)
np.delete(a, (a%3==0).astype(np.uint8))

array([2, 3, 4, 5, 6, 7, 8, 9])

In [348]:
a = np.arange(6) + np.arange(0,51,10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [344]:
# get by rows and columns
a[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [356]:
a[(1,0,1),(2,3,1)]

array([12,  3, 11])

In [357]:
a[(1,0,1,0),:]

array([[10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5]])

In [346]:
np.take(a, ((0,1,2,3,4),(1,2,3,4,5)))

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5]])

In [345]:
a[3:,[0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [188]:
a.flat[8]

12

In [189]:
a = np.arange(6) + np.arange(0,51,10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [190]:
# get by mask
mask = np.array([1,0,1,0,0,1], dtype=bool)
mask

array([ True, False,  True, False, False,  True], dtype=bool)

In [191]:
a[mask, 2]

array([ 2, 22, 52])

In [192]:
mask = a%2==1
mask

array([[False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]], dtype=bool)

In [193]:
a[mask]

array([ 1,  3,  5, 11, 13, 15, 21, 23, 25, 31, 33, 35, 41, 43, 45, 51, 53,
       55])

In [194]:
mask2 = a%3==0
mask2

array([[ True, False, False,  True, False, False],
       [False, False,  True, False, False,  True],
       [False,  True, False, False,  True, False],
       [ True, False, False,  True, False, False],
       [False, False,  True, False, False,  True],
       [False,  True, False, False,  True, False]], dtype=bool)

In [195]:
masks = np.logical_and(mask, mask2)

In [196]:
masks

array([[False, False, False,  True, False, False],
       [False, False, False, False, False,  True],
       [False,  True, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False,  True],
       [False,  True, False, False, False, False]], dtype=bool)

In [197]:
a[masks]

array([ 3, 15, 21, 33, 45, 51])

#### Exercise
Create a 10x10 array with np.arange, elements between 0 to 100 and get the numbers greater than 50 and divisible to 7.

Input:
```python
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
```
Expected output:
```python
array([56, 63, 70, 77, 84, 91, 98])
```

In [199]:
a = np.arange(100).reshape((10,10))
a[np.logical_and(a>50, a%7==0)]

array([56, 63, 70, 77, 84, 91, 98])

## View Copy

In [228]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [232]:
# slicing does not copy
b = a[::2]
b

array([12,  2,  4,  6,  8])

In [233]:
np.may_share_memory(a, b)

True

In [234]:
b[0] = 12
print(a)
print(b)

[12  1  2  3  4  5  6  7  8  9]
[12  2  4  6  8]


In [235]:
a = np.arange(10)
c = a[::2].copy()

In [236]:
np.may_share_memory(a, c)

False

In [237]:
c[0] = 12
print(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[12  2  4  6  8]


## Broadcasting

<img src='../img/numpy_broadcasting.png'>

In [223]:
a = np.arange(0, 40, 10)
b = np.array([0, 1, 2])

In [224]:
a.shape

(4,)

In [225]:
b.shape

(3,)

In [226]:
a + b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [227]:
c = a[:, np. newaxis] # adds a new axis -> 2D array
c.shape

(4, 1)

In [228]:
c

array([[ 0],
       [10],
       [20],
       [30]])

In [232]:
d = b + c
d

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [235]:
d.shape

(4, 3)

In [236]:
d[:, np.newaxis].shape

(4, 1, 3)

In [234]:
d[:, np.newaxis] + np.arange(0,300,100)

array([[[  0, 101, 202]],

       [[ 10, 111, 212]],

       [[ 20, 121, 222]],

       [[ 30, 131, 232]]])

https://github.com/rougier/numpy-tutorial#quick-references

#### Exercise
Create the following 4x5 array by broadcasting and array addition.

```python
array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])
```

In [20]:
np.arange(5) + np.arange(10,50,10)[:,np.newaxis]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

#### Exercise
Create the following 2x4x5 array by broadcasting and array addition.

```python
array([[[110, 111, 112, 113, 114],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144]],

       [[210, 211, 212, 213, 214],
        [220, 221, 222, 223, 224],
        [230, 231, 232, 233, 234],
        [240, 241, 242, 243, 244]]])
```

In [24]:
x = np.arange(5) + np.arange(10,50,10)[:,np.newaxis] + np.arange(100,300,100)[:,np.newaxis, np.newaxis]
x

array([[[110, 111, 112, 113, 114],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144]],

       [[210, 211, 212, 213, 214],
        [220, 221, 222, 223, 224],
        [230, 231, 232, 233, 234],
        [240, 241, 242, 243, 244]]])

## Mesh

In [10]:
x, y = np.ogrid[ 0:5 , 0:5 ]
print(x, x.shape)
print()
print(y, y.shape)

[[0]
 [1]
 [2]
 [3]
 [4]] (5, 1)

[[0 1 2 3 4]] (1, 5)


In [11]:
np.sqrt(x**2 + y**2)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.41421356,  2.23606798,  3.16227766,  4.12310563],
       [ 2.        ,  2.23606798,  2.82842712,  3.60555128,  4.47213595],
       [ 3.        ,  3.16227766,  3.60555128,  4.24264069,  5.        ],
       [ 4.        ,  4.12310563,  4.47213595,  5.        ,  5.65685425]])

In [12]:
x, y = np.mgrid[0:3, 10:40:10]

In [13]:
x

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [14]:
y

array([[10, 20, 30],
       [10, 20, 30],
       [10, 20, 30]])

In [15]:
np.sqrt(x**2 + y**2)

array([[ 10.        ,  20.        ,  30.        ],
       [ 10.04987562,  20.02498439,  30.01666204],
       [ 10.19803903,  20.09975124,  30.06659276]])

In [16]:
aa, bb, cc = np.ogrid[0:1:2j, 0:1:5j, 0:1:3j]

In [17]:
aa, bb, cc

(array([[[ 0.]],
 
        [[ 1.]]]), array([[[ 0.  ],
         [ 0.25],
         [ 0.5 ],
         [ 0.75],
         [ 1.  ]]]), array([[[ 0. ,  0.5,  1. ]]]))

#### Exercise
Find the distance of each point to origin in a cube centered on the point (2,-3, 1) and has length of 4.

In [3]:
cx, cy, cz = 2, -3, 1 # center point of cube
w = 4 # width

u = w/2
x, y, z = np.ogrid[ (cx-u):(cx+u) , (cy-u):(cy+u), (cz-u):(cz+u)]
np.sqrt(x**2 + y**2 + z**2)

array([[[ 5.09901951,  5.        ,  5.09901951,  5.38516481],
        [ 4.12310563,  4.        ,  4.12310563,  4.47213595],
        [ 3.16227766,  3.        ,  3.16227766,  3.60555128],
        [ 2.23606798,  2.        ,  2.23606798,  2.82842712]],

       [[ 5.19615242,  5.09901951,  5.19615242,  5.47722558],
        [ 4.24264069,  4.12310563,  4.24264069,  4.58257569],
        [ 3.31662479,  3.16227766,  3.31662479,  3.74165739],
        [ 2.44948974,  2.23606798,  2.44948974,  3.        ]],

       [[ 5.47722558,  5.38516481,  5.47722558,  5.74456265],
        [ 4.58257569,  4.47213595,  4.58257569,  4.89897949],
        [ 3.74165739,  3.60555128,  3.74165739,  4.12310563],
        [ 3.        ,  2.82842712,  3.        ,  3.46410162]],

       [[ 5.91607978,  5.83095189,  5.91607978,  6.164414  ],
        [ 5.09901951,  5.        ,  5.09901951,  5.38516481],
        [ 4.35889894,  4.24264069,  4.35889894,  4.69041576],
        [ 3.74165739,  3.60555128,  3.74165739,  4.12310563]]])

In [6]:
cx, cy, cz = 0,0,0 # center point of cube
w = 4 # width

u = w/2
x, y, z = np.mgrid[ (cx-u):(cx+u) , (cy-u):(cy+u), (cz-u):(cz+u)]
np.sqrt(x**2 + y**2 + z**2)

array([[[ 3.46410162,  3.        ,  2.82842712,  3.        ],
        [ 3.        ,  2.44948974,  2.23606798,  2.44948974],
        [ 2.82842712,  2.23606798,  2.        ,  2.23606798],
        [ 3.        ,  2.44948974,  2.23606798,  2.44948974]],

       [[ 3.        ,  2.44948974,  2.23606798,  2.44948974],
        [ 2.44948974,  1.73205081,  1.41421356,  1.73205081],
        [ 2.23606798,  1.41421356,  1.        ,  1.41421356],
        [ 2.44948974,  1.73205081,  1.41421356,  1.73205081]],

       [[ 2.82842712,  2.23606798,  2.        ,  2.23606798],
        [ 2.23606798,  1.41421356,  1.        ,  1.41421356],
        [ 2.        ,  1.        ,  0.        ,  1.        ],
        [ 2.23606798,  1.41421356,  1.        ,  1.41421356]],

       [[ 3.        ,  2.44948974,  2.23606798,  2.44948974],
        [ 2.44948974,  1.73205081,  1.41421356,  1.73205081],
        [ 2.23606798,  1.41421356,  1.        ,  1.41421356],
        [ 2.44948974,  1.73205081,  1.41421356,  1.73205081]]])