# Numpy

[www.numpy.org](http://www.numpy.org)

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

In [1]:
import numpy as np

### Fast and memory efficient 

In [2]:
L = range(1000)
%timeit [i**2 for i in L]

290 µs ± 2.22 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
a = np.arange(1000)
%timeit a**2

1.17 µs ± 25.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Numpy Reference documentation

In [4]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [5]:
np.con*?

### Creating arrays

In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.ndim

1

In [9]:
b = np.array([[0 , 1 , 2 ], [3 , 4 , 5 ]]) # 2 x 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
print('Array:\n', b, '\n')
print('Number of dimensions:\t', b.ndim)
print('Shape:\t\t\t', b.shape)
print('Array size:\t\t', b.size)
print('Element type:\t\t', b.dtype)
print('Element memory size:\t', b.itemsize, '  (in bytes)')
print('Array memory size:\t', b.nbytes, ' (in bytes)')

Array:
 [[0 1 2]
 [3 4 5]] 

Number of dimensions:	 2
Shape:			 (2, 3)
Array size:		 6
Element type:		 int64
Element memory size:	 8   (in bytes)
Array memory size:	 48  (in bytes)


In [11]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))

List to array: 
[1 2 3 4 5 6 7 8]


In [12]:
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))

Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [34]:
x = np.arange(10, dtype=np.uint8)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [35]:
x.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
bs = x.tobytes()
bs

b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t'

In [37]:
np.fromstring(bs, dtype=np.uint8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [16]:
c = np.array([[0, 1, 2], [3, 4, 5]], dtype=np.int8)

In [38]:
c.itemsize

1

In [39]:
d = np.array( [ [1,2], [3,4] ], dtype=np.complex )

In [40]:
d

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [41]:
d.itemsize

16

In [42]:
o = np.array([1, 'abcd', None, 2.1])

In [43]:
o.itemsize

8

In [44]:
np.arange(1 , 9 , 2 ) # start, end (exclusive), step

array([1, 3, 5, 7])

In [45]:
np.arange( 0, 2, 0.3 ) # it accepts float arguments

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [46]:
# linearly spaced
np.linspace(0 , 1 , 6 ) # start, end, number of points

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [47]:
# logarithmically spaced
np.logspace(2 , 10 , 3 ) # start, end, number of points

array([  1.00000000e+02,   1.00000000e+06,   1.00000000e+10])

In [48]:
np.ones((3, 3)) # reminder: (3, 3) is a tuple

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [49]:
np.zeros((2, 2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [50]:
# creates an array whose initial content is random and depends on the state of the memory
np.empty((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [299]:
# identity array
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [52]:
np.diag(np.array([1 ,2 ,3 ,4 ]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [53]:
np.tri(3,4)

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.]])

In [54]:
np.tri(3,4, 0)

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.]])

In [55]:
np.tri(3,4,1)

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  1.,  1.]])

In [56]:
np.tri(3,4,-1)

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.]])

In [57]:
np.tri(3,4,-2)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.]])

In [58]:
np.tri?

In [59]:
np.triu(np.ones(3))

array([[ 1.,  1.,  1.],
       [ 0.,  1.,  1.],
       [ 0.,  0.,  1.]])

In [62]:
np.triu(np.ones(3),1)

array([[ 0.,  1.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [63]:
np.random.seed(1234)

In [64]:
np.random.rand(4) # uniform in [0, 1]

array([ 0.19151945,  0.62210877,  0.43772774,  0.78535858])

In [65]:
np.random.randn(4) # Gaussian

array([-0.72058873,  0.88716294,  0.85958841, -0.6365235 ])

In [66]:
np.random.randint(0 , 20, 10 )

array([12, 16,  5, 16,  9, 15, 18, 16, 12,  5])

In [389]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [390]:
np.random.shuffle(x)
x

array([7, 2, 3, 1, 6, 4, 0, 9, 8, 5])

#### Exercise
Create this 2D array.
```python
array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  9,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 15,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 18,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 21,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 24]])
```

In [70]:
np.diag(np.arange(0,27,3))

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  9,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 15,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 18,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 21,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 24]])

### Basic data types

In [71]:
a = np.array([1 , 2 , 3 ])
a.dtype

dtype('int64')

In [72]:
b = np.array([ 0.1, 2., 3.6])
b.dtype

dtype('float64')

In [73]:
b.itemsize

8

In [74]:
x = b.astype(int)
x

array([0, 2, 3])

In [75]:
x.itemsize

8

In [76]:
x.dtype

dtype('int64')

In [77]:
x = b.astype(np.int8)

In [78]:
x.itemsize

1

In [79]:
c = np.array([1 , 2 , 3 ], dtype = float )
c.dtype

dtype('float64')

In [80]:
d = np.array([1 + 2j, 3 + 4j, 5 + 6 * 1j ])
d.dtype

dtype('complex128')

In [81]:
e = np.array([True, False , False , True])
e.dtype

dtype('bool')

In [82]:
e.itemsize

1

In [83]:
f = np.array(['Bonjour' , ' Hello' , ' Hallo' ,])
f.dtype # <--- strings containing max. 7 letters

dtype('<U7')

In [84]:
f.itemsize

28

In [85]:
g = np.array(['Bonjour Madam' ,'çğıöüş'])
g.dtype # <--- strings containing max. 21 letters

dtype('<U13')

In [86]:
g.itemsize

52

#### Exercise
Create an array ranging from 0 to 10 with 0.5 step size and then convert it to integer array.

In [87]:
np.arange(0, 10, 0.5).astype(np.uint8)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9], dtype=uint8)

### reshape resize newaxis tile

In [88]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
x.shape

(12,)

In [90]:
x.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
x.shape

(12,)

In [92]:
x.reshape((6,-1))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [93]:
x.reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [94]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [95]:
x.resize((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
row_vector = np.arange(6)
print(row_vector)
print(row_vector.ndim)
print(row_vector.shape)

[0 1 2 3 4 5]
1
(6,)


In [99]:
row_vector.T

array([0, 1, 2, 3, 4, 5])

In [122]:
row_vector[:]

array([0, 1, 2, 3, 4, 5])

In [123]:
row_vector[:,:]

IndexError: too many indices for array

In [119]:
row_array = row_vector[:, np.newaxis]
row_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [121]:
print(row_vector.shape)
print(row_array.shape)

(6,)
(6, 1)


In [112]:
column_array = np.arange(0, 51, 10).reshape((-1,1))
print(column_array)
print(column_array.ndim)
print(column_array.shape)

[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
2
(6, 1)


In [113]:
column_array.T

array([[ 0, 10, 20, 30, 40, 50]])

In [114]:
column_array.T.shape

(1, 6)

In [110]:
column_vector

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [115]:
column_array

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [116]:
np.arange(0, 51, 10)[:, np.newaxis]

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [118]:
# broadcasting
row_vector + column_array

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

#### Exercise
Create the following 3x4 matrix.

Expected Output:
```python
array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])
``` 

In [131]:
np.arange(1,13).reshape((3,4))*3

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [130]:
np.arange(3,37,3).reshape((3,4))

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

### Indexing and slicing

<img src='../img/numpy_array_slicing.png'>

In [132]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
a[2]

2

In [134]:
b = np.diag(np.arange(3))
b

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [135]:
b[1, 1]

1

In [136]:
a[0:4]

array([0, 1, 2, 3])

In [137]:
a[-4:-1]

array([6, 7, 8])

In [138]:
# reversed
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [139]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
a[2:9:3] # [start:end:step]

array([2, 5, 8])

In [141]:
a = np.arange(6) + np.arange(0,51,10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [142]:
a[0,3:5]

array([3, 4])

In [143]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [144]:
a[2:]

array([[20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [145]:
a[:,:2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51]])

In [146]:
slice?

In [147]:
slice(0,10,3)

slice(0, 10, 3)

In [148]:
np.arange(10)[slice(0,10,3)]

array([0, 3, 6, 9])

In [149]:
np.s_?

In [150]:
np.s_[0:10:3]

slice(0, 10, 3)

In [151]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
a[1] = 11

In [153]:
a

array([ 0, 11,  2,  3,  4,  5,  6,  7,  8,  9])

In [154]:
a[2:5] = [22,33,44]

In [155]:
a

array([ 0, 11, 22, 33, 44,  5,  6,  7,  8,  9])

In [156]:
a[2:5] = np.array([-2,-3,-4])

In [157]:
a

array([ 0, 11, -2, -3, -4,  5,  6,  7,  8,  9])

In [158]:
# assignment does match the length of slice
a[6:9] = np.array([-6,-7])

ValueError: could not broadcast input array from shape (2) into shape (3)

In [159]:
a

array([ 0, 11, -2, -3, -4,  5,  6,  7,  8,  9])

In [160]:
# assignment does match the length of slice
a[6:9] = np.array([-6])

In [161]:
a

array([ 0, 11, -2, -3, -4,  5, -6, -6, -6,  9])

In [162]:
np.delete(a, [8,9])

array([ 0, 11, -2, -3, -4,  5, -6, -6])

In [163]:
a

array([ 0, 11, -2, -3, -4,  5, -6, -6, -6,  9])

In [164]:
np.delete(a, np.s_[0:3])

array([-3, -4,  5, -6, -6, -6,  9])

In [165]:
tda = np.arange(20).reshape((4,-1))
tda

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [166]:
np.delete(tda, (1,2), axis=0)

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [167]:
np.delete(tda, (1,2), axis=1)

array([[ 0,  3,  4],
       [ 5,  8,  9],
       [10, 13, 14],
       [15, 18, 19]])

#### Exercise
Write a Python program to create a 2d array with 1 on the border and 0 inside.

Original array: 
```
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)
```
Expected Output:
```
array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)
```

In [168]:
a = np.ones((5,5), dtype=np.uint8)
a[1:-1,1:-1]=0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

#### Exercise
Write a Python program to create a 2d array with 0 on the border and 1 inside.

Original array: 
```python
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8) 
```

Expected Output:
```python
array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)
```

In [169]:
a = np.ones((5,5), dtype=np.uint8)
a[0,:] = 0
a[-1,:] = 0
a[:,0] = 0
a[:,-1] = 0
a

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

#### Exercise
Write a Python program to pad a given 2D given array with 0.

Original array: 
```python
array([[ 4, 11,  9, 19],
       [ 8, 12,  0, 12],
       [ 7,  1, 16,  3]])
```

Expected Output:
```python
array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  4, 11,  9, 19,  0],
       [ 0,  8, 12,  0, 12,  0],
       [ 0,  7,  1, 16,  3,  0],
       [ 0,  0,  0,  0,  0,  0]])
```

In [170]:
a = np.random.randint(0,20,12).reshape((3,4))
nr, nc = a.shape
b = np.zeros((nr+2, nc+2))
b[1:-1,1:-1] = a

print(a)
print()
print(b.astype(np.uint8))

[[ 2  6  3  7]
 [11  0  9 11]
 [16  3  2 19]]

[[ 0  0  0  0  0  0]
 [ 0  2  6  3  7  0]
 [ 0 11  0  9 11  0]
 [ 0 16  3  2 19  0]
 [ 0  0  0  0  0  0]]


#### Exercise
Create the 2D array below by using reshape and delete operations.

```python
array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])
``` 

In [171]:
a = np.arange(60).reshape((6,-1))
b = np.delete(a, (6,7,8,9), axis=1)
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

#### Exercise
Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

Expected Output:
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [172]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=np.uint8)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Example

In [173]:
is_prime = np.ones((100, ))

In [174]:
is_prime[:2] = 0
is_prime

array([ 0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [175]:
N_max = int(np.sqrt(len(is_prime)))
for j in range(2,N_max):
    is_prime[j*j::j] = 0

In [176]:
is_prime

array([ 0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
        1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.])

In [177]:
np.nonzero(is_prime)

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
        61, 67, 71, 73, 79, 83, 89, 97]),)

### Fancy indexing

<img src='../img/numpy_fancy_indexing.png'>

In [178]:
a = np.arange(10)

In [179]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool)

In [180]:
mask = (a % 2 == 0)

In [181]:
mask

array([ True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool)

In [182]:
a[mask]

array([0, 2, 4, 6, 8])

In [183]:
a = np.arange(10)
np.delete(a, (a%3==0).astype(np.uint8))

array([2, 3, 4, 5, 6, 7, 8, 9])

In [348]:
a = np.arange(6) + np.arange(0,51,10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [344]:
# get by rows and columns
a[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [356]:
a[(1,0,1),(2,3,1)]

array([12,  3, 11])

In [357]:
a[(1,0,1,0),:]

array([[10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5]])

In [346]:
np.take(a, ((0,1,2,3,4),(1,2,3,4,5)))

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5]])

In [345]:
a[3:,[0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [188]:
a.flat[8]

12

In [189]:
a = np.arange(6) + np.arange(0,51,10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [190]:
# get by mask
mask = np.array([1,0,1,0,0,1], dtype=bool)
mask

array([ True, False,  True, False, False,  True], dtype=bool)

In [191]:
a[mask, 2]

array([ 2, 22, 52])

In [192]:
mask = a%2==1
mask

array([[False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]], dtype=bool)

In [193]:
a[mask]

array([ 1,  3,  5, 11, 13, 15, 21, 23, 25, 31, 33, 35, 41, 43, 45, 51, 53,
       55])

In [194]:
mask2 = a%3==0
mask2

array([[ True, False, False,  True, False, False],
       [False, False,  True, False, False,  True],
       [False,  True, False, False,  True, False],
       [ True, False, False,  True, False, False],
       [False, False,  True, False, False,  True],
       [False,  True, False, False,  True, False]], dtype=bool)

In [195]:
masks = np.logical_and(mask, mask2)

In [196]:
masks

array([[False, False, False,  True, False, False],
       [False, False, False, False, False,  True],
       [False,  True, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False,  True],
       [False,  True, False, False, False, False]], dtype=bool)

In [197]:
a[masks]

array([ 3, 15, 21, 33, 45, 51])

#### Exercise
Create a 10x10 array with np.arange, elements between 0 to 100 and get the numbers greater than 50 and divisible to 7.

Input:
```python
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
```
Expected output:
```python
array([56, 63, 70, 77, 84, 91, 98])
```

In [199]:
a = np.arange(100).reshape((10,10))
a[np.logical_and(a>50, a%7==0)]

array([56, 63, 70, 77, 84, 91, 98])

### 3 dimensional Arrays

In [200]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [201]:
a.shape

(2, 3, 4)

In [202]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [203]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [204]:
a[0].shape

(3, 4)

In [205]:
a[0,0:2,2:]

array([[2, 3],
       [6, 7]])

In [206]:
a[...,2]

array([[ 2,  6, 10],
       [14, 18, 22]])

In [207]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]
              ]
            )
print(c)
print()
print(c.shape)

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]

(2, 2, 3)


In [208]:
# ellipsis operator
c[1,...] # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [209]:
c[...,2] # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

In [210]:
b = a.sum(axis=0)
b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [211]:
b.sum(axis=1)

array([ 60,  92, 124])

### Membership 

In [216]:
1 in np.arange(10)

True

In [217]:
np.array([1,2]) in np.arange(10)

/Users/bdsaglam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [300]:
large = np.arange(5)
small = np.array([2,4,6])

In [301]:
np.in1d(large, small)

array([False, False,  True, False,  True], dtype=bool)

In [302]:
np.in1d(small, large)

array([ True,  True, False], dtype=bool)

## Iteration
Iterating over multidimensional arrays is done with respect to the first axis.

In [224]:
a = np.arange(12).reshape(3,4)
for row in a:
    print(row)
    print("----------------")

[0 1 2 3]
----------------
[4 5 6 7]
----------------
[ 8  9 10 11]
----------------


In [309]:
for i,row in enumerate(a):
    print("row ",i)
    print("----------------")
    print(row)

row  0
----------------
4
row  1
----------------
3
row  2
----------------
1
row  3
----------------
2


In [227]:
a = np.arange(12).reshape(3,2,2)
a.shape

(3, 2, 2)

In [225]:
for element in a.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11


#### Exercise
Create a 5x5 zero array and with a number n given by user, change nth element of first row, n+1 element for the next row, so on. Return to beginning of the row it exceeds the row size.

Input:
```python
x = np.zeros((5,5))
n = 2
```

Expected output:
```python
array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.]])
```


In [318]:
x = np.zeros((5,5))
n = 2
for i,row in enumerate(x):
    x[i,(i+n)%5] = 1
x

array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.]])

### Copies and views

In [228]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [232]:
# slicing does not copy
b = a[::2]
b

array([12,  2,  4,  6,  8])

In [233]:
np.may_share_memory(a, b)

True

In [234]:
b[0] = 12
print(a)
print(b)

[12  1  2  3  4  5  6  7  8  9]
[12  2  4  6  8]


In [235]:
a = np.arange(10)
c = a[::2].copy()

In [236]:
np.may_share_memory(a, c)

False

In [237]:
c[0] = 12
print(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[12  2  4  6  8]


###  Operations

In [276]:
x = np.array([1,2,3])
y = np.array([0,5,10])
z = np.array([4,8,16,32])

In [281]:
x + 10

array([11, 12, 13])

In [277]:
x*2

array([2, 4, 6])

In [278]:
x/2

array([ 0.5,  1. ,  1.5])

In [279]:
x**2

array([1, 4, 9])

In [286]:
np.sqrt(x)

array([ 1.        ,  1.41421356,  1.73205081])

In [242]:
x*y

array([ 0, 10, 30])

In [243]:
x*z

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [244]:
p = np.ones((3, 3))
w = np.arange(9).reshape((3,3))
p*w

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [245]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [246]:
a + b

array([5, 4, 5, 8])

In [247]:
a == b

array([False,  True, False,  True], dtype=bool)

In [248]:
np.in1d(a,b)

array([False,  True, False,  True], dtype=bool)

In [249]:
a > b

array([False, False,  True, False], dtype=bool)

In [250]:
a.dot(b)

30

In [252]:
a = np.array([[1, 2, 3], [3, 4, 5]])
b = np.array([1,1,1])

In [253]:
a.shape

(2, 3)

In [254]:
b.shape

(3,)

In [255]:
a.dot(b)

array([ 6, 12])

In [256]:
a.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [259]:
a.T.dot(b)

ValueError: shapes (3,2) and (6,) not aligned: 2 (dim 1) != 6 (dim 0)

In [257]:
a.conj()

array([[1, 2, 3],
       [3, 4, 5]])

In [263]:
x = np.eye(2) + 1j * np.eye(2)
x

array([[ 1.+1.j,  0.+0.j],
       [ 0.+0.j,  1.+1.j]])

In [264]:
np.conjugate(x)

array([[ 1.-1.j,  0.-0.j],
       [ 0.-0.j,  1.-1.j]])

In [265]:
a = np.array([[1, 2, 3], [3, 4, 5]])
b = a.flatten()
b

array([1, 2, 3, 3, 4, 5])

In [266]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [267]:
np.ravel(a)

array([1, 2, 3, 3, 4, 5])

In [268]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [269]:
a = np.array([1 , 1 , 0 , 0 ], dtype = bool)
b = np.array([1 , 0 , 1 , 0 ], dtype = bool)

In [271]:
a

array([ True,  True, False, False], dtype=bool)

In [272]:
np.logical_or(a, b)

array([ True,  True,  True, False], dtype=bool)

In [273]:
np.logical_and(a, b)

array([ True, False, False, False], dtype=bool)

In [287]:
a = np.array([4, 3, 1, 2])
a

array([4, 3, 1, 2])

In [288]:
a.sum()

10

In [289]:
d = np.arange(12).reshape(3,4)

In [290]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [291]:
# row-wise
d.sum(axis=0)

array([12, 15, 18, 21])

In [292]:
# column-wise
d.sum(axis=1)

array([ 6, 22, 38])

In [330]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [331]:
np.linalg.det(x)

-2.0000000000000004

In [332]:
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#### Exercise
Solve following equations.

```
x + 2y = 1
3x + 4y = 10
```


In [327]:
m = np.array([[1,2],[3,4]])
n = np.array([1,10])

In [328]:
np.linalg.inv(m)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [329]:
np.linalg.inv(m).dot(n)

array([ 8. , -3.5])

### Extremes and sorting

In [391]:
x = np.array([1, 3, 2])

In [392]:
print(x.min())
print(x.argmin())

1
0


In [393]:
print(x.max())
print(x.argmax())

3
1


In [394]:
a = np.array([[4 , 2 , 5 ], [1 , 3 , 0 ]])
a

array([[4, 2, 5],
       [1, 3, 0]])

In [395]:
a.max(axis=0)

array([4, 3, 5])

In [396]:
a.min(axis=1)

array([2, 0])

In [397]:
np.sort?

In [398]:
a = np.array([[4 , 2 , 5 ], [1 , 3 , 0 ]])
a

array([[4, 2, 5],
       [1, 3, 0]])

In [399]:
np.sort(a, axis=0)

array([[1, 2, 0],
       [4, 3, 5]])

In [400]:
np.sort(a, axis=1)

array([[2, 4, 5],
       [0, 1, 3]])

In [401]:
a.sort(axis=0)
a

array([[1, 2, 0],
       [4, 3, 5]])

In [402]:
a = np.array([4, 3, 1, 2])
np.argsort(a)

array([2, 3, 1, 0])

In [403]:
people = np.array(['A', 'B', 'C', 'D'])
ages = np.array([32, 19, 24, 45])

indices = np.argsort(ages)
indices

array([1, 2, 0, 3])

In [404]:
people[indices]

array(['B', 'C', 'A', 'D'],
      dtype='<U1')

In [426]:
a = np.array([[4 , 2 , 5 ], 
              [1 , 3 , 0 ],
              [7 , 1 , 3 ],])
np.argsort(a, axis=0)

array([[1, 2, 1],
       [0, 0, 2],
       [2, 1, 0]])

In [444]:
a[np.argsort(a, axis=0)[:,0]]

array([[1, 3, 0],
       [4, 2, 5],
       [7, 1, 3]])

In [447]:
a

array([[4, 2, 5],
       [1, 3, 0],
       [7, 1, 3]])

In [450]:
# indices = np.nonzero(np.argsort(a, axis=0))
indices = np.unravel_index(np.argsort(a, axis=0), a.shape)
print(type(indices))
print(len(indices))
print(indices[0])
print(indices[1])

<class 'tuple'>
2
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 2 1]
 [0 0 2]
 [2 1 0]]


In [453]:
cols, rows = indices

In [454]:
a[rows[:,0],:]

array([[1, 3, 0],
       [4, 2, 5],
       [7, 1, 3]])

#### Exercise
Find the year with maximum export in 10 years for each country.

Input:
```python
# row - year, column - country
years = np.arange(2007,2018)
countries = np.array(['US','UK', 'Canada', 'Australia', 'Germany','Japan','Korea','India','Brazil', 'South Africa'])
export_array = np.random.randint(10,100,100).reshape((10,10))
```

Expected output:
```python
[('US', 2008),
 ('UK', 2012),
 ('Canada', 2015),
 ('Australia', 2016),
 ('Germany', 2008),
 ('Japan', 2014),
 ('Korea', 2016),
 ('India', 2014),
 ('Brazil', 2014),
 ('South Africa', 2010)]
```

In [378]:
# row - year, column - country
years = np.arange(2007,2018)
countries = np.array(['US','UK', 'Canada', 'Australia', 'Germany','Japan','Korea','India','Brazil', 'South Africa'])
export_array = np.random.randint(10,100,100).reshape((10,10))

In [379]:
best_years = export_array.argmax(axis=0)
list(zip(countries, years[best_years]))

[('US', 2014),
 ('UK', 2012),
 ('Canada', 2016),
 ('Australia', 2012),
 ('Germany', 2009),
 ('Japan', 2010),
 ('Korea', 2012),
 ('India', 2014),
 ('Brazil', 2016),
 ('South Africa', 2009)]

## unique all any

In [ ]:
np.unique(np.array([1,2,2,3,4,5,2,3,4]))

In [ ]:
np.all([ True, True, False ])

In [ ]:
np.any([ True, True, False ])

In [ ]:
a = np.array([1 , 2 , 3 , 2 ])
b = np.array([2 , 2 , 3 , 2 ])
c = np.array([6 , 4 , 4 , 5 ])
((a <= b) & (b <= c)).all()

#### Exercise
Create the array defined below and give all rows containing a number that is divisible to 9.

Input:
```python
array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])
```

Expected output:
```python
array([[ 0,  1,  2,  3,  4,  5],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])
```

In [380]:
a = np.arange(6) + np.arange(0,51,10)[:, np.newaxis]
mask = a%9==0

a[np.any(mask, axis=1),:]

array([[ 0,  1,  2,  3,  4,  5],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [381]:
mask

array([[ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False,  True, False]], dtype=bool)

In [ ]:
x = np.array([4,0,-1,0,12,9])
x

In [ ]:
indices = np.nonzero(x)
indices

In [ ]:
x[indices]

In [ ]:
x < 5

In [ ]:
np.nonzero(x < 5)

In [ ]:
x = np.arange(12).reshape(3,4)

In [ ]:
rows, columns = np.where(x < 5)
print(rows)
print(columns)

In [ ]:
x[rows, columns]

In [ ]:
ix = np.isin(x, [3, 4, 7])
print(ix)

In [ ]:
np.where(ix)

In [ ]:
np.where(x < 5, x, -1)  # Note: broadcasting.

In [ ]:
np.where([[True, False], [True, True]],
          [[1, 2], [3, 4]],
          [[9, 8], [7, 6]])

#### Exercise
Create the array defined below and give all columns containing a number that is divisible to 9.

Input:
```python
array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])
```

Expected output:
```python
array([[ 0,  5,  4],
       [10, 15, 14],
       [20, 25, 24],
       [30, 35, 34],
       [40, 45, 44],
       [50, 55, 54]])
```

In [383]:
a = np.arange(6) + np.arange(0,51,10)[:, np.newaxis]
rows, columns = np.nonzero(a%9==0)

a[:,columns]

array([[ 0,  5,  4],
       [10, 15, 14],
       [20, 25, 24],
       [30, 35, 34],
       [40, 45, 44],
       [50, 55, 54]])

In [384]:
a = np.arange(6) + np.arange(0,51,10)[:, np.newaxis]
rows, columns = np.where(a%9==0)

a[:,columns]

array([[ 0,  5,  4],
       [10, 15, 14],
       [20, 25, 24],
       [30, 35, 34],
       [40, 45, 44],
       [50, 55, 54]])

## Basic statistics

In [ ]:
x = np.array([1 , 2 , 3 , 1 ])
y = np.array([[1 , 2 , 3 ], [5 , 6 , 1 ]])

In [ ]:
x.mean()

In [ ]:
np.median(x)

In [ ]:
np.median(y, axis = - 1 ) # last axis

In [ ]:
x.std() # full population standard dev.