# Numpy

In [2]:
import numpy as np

In [3]:
def iprint(seq, sep='--------'):
    for item in seq:
        print(item)
        print(sep)

# Operations

##  Array (Element-wise) Operations 

In [4]:
x = np.array([1,2,3])
y = np.array([0,5,10])
z = np.array([4,8,16,32])

In [5]:
x + 10

array([11, 12, 13])

In [6]:
x*2

array([2, 4, 6])

In [7]:
x/2

array([ 0.5,  1. ,  1.5])

In [8]:
x**2

array([1, 4, 9])

In [9]:
np.sqrt(x)

array([ 1.        ,  1.41421356,  1.73205081])

In [10]:
x*y

array([ 0, 10, 30])

In [11]:
x*z

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [12]:
p = np.ones((3, 3))
w = np.arange(9).reshape((3,3))
p*w

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [14]:
a + b

array([5, 4, 5, 8])

In [15]:
a == b

array([False,  True, False,  True], dtype=bool)

In [16]:
np.in1d(a,b)

array([False,  True, False,  True], dtype=bool)

In [17]:
a > b

array([False, False,  True, False], dtype=bool)

In [18]:
a = np.array([1 , 1 , 0 , 0 ], dtype = bool)
b = np.array([1 , 0 , 1 , 0 ], dtype = bool)

In [19]:
a

array([ True,  True, False, False], dtype=bool)

In [20]:
np.logical_or(a, b)

array([ True,  True,  True, False], dtype=bool)

In [21]:
np.logical_and(a, b)

array([ True, False, False, False], dtype=bool)

In [22]:
a = np.array([7, 2, 5, -1, 0, 3, -4])
a.clip(0, 5)

array([5, 2, 5, 0, 0, 3, 0])

In [23]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
out = np.trim_zeros(a)
out

array([1, 2, 3, 0, 2, 1])

#### Exercise
From 3 arrays representing age, revenue, and names. Filter the firms that age below 10 and have revenue over $10M.

```python
ages = np.array([7,8,9,10,11])
revenues = np.array([15, 22, 8, 12, 15])
firms = np.array(['A','G','Z','M','F'])
```

In [24]:
ages = np.array([7,8,9,10,11])
revenues = np.array([15, 22, 8, 12, 15])
firms = np.array(['A','G','Z','M','F'])
firms[np.logical_and(ages<10, revenues>10)]

array(['A', 'G'],
      dtype='<U1')

### Membership 

In [25]:
1 in np.arange(10)

True

In [26]:
np.array([1,2]) in np.arange(10)

/Users/bdsaglam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [27]:
x = np.arange(5)
y = np.array([2,4,6])

In [28]:
np.in1d(x, y) # look elements of x in y

array([False, False,  True, False,  True], dtype=bool)

In [29]:
np.in1d(y, x) # look elements of y in x

array([ True,  True, False], dtype=bool)

### Logical Operations

### all any

In [40]:
x = np.random.randint(0,2,12).reshape(3,4).astype(bool)

In [41]:
x

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [False,  True, False,  True]], dtype=bool)

In [43]:
np.all(x, axis=1)

array([False,  True, False], dtype=bool)

In [30]:
np.all([ True, True, False ])

False

In [31]:
np.any([ True, True, False ])

True

In [32]:
a = np.array([1 , 2 , 3 , 2 ])
b = np.array([2 , 2 , 3 , 2 ])
c = np.array([6 , 4 , 4 , 5 ])
((a <= b) & (b <= c)).all()

True

#### Exercise
Create the array defined below and give all rows containing a number that is divisible to 9.

Input:
```python
array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])
```

Expected output:
```python
array([[ 0,  1,  2,  3,  4,  5],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])
```

In [380]:
mask = a%9==0

a[np.any(mask, axis=1),:]

array([[ 0,  1,  2,  3,  4,  5],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [381]:
mask

array([[ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False,  True, False]], dtype=bool)

#### Exercise

Take two lists, find the indices where the second is matched in the first.

Verilen iki listeden ikincisinin birinci listede hangi indexlerde eşleştiğini yazan bir program yazın. Program eğer hiç eşleşme yoksa boş liste verebilir.

```
Input: [0,0,1,1,0,1,1,0,1,0,1] and [1,0,1]
Expected output: [3,6,8]

Input: [0,1,1,0,1,1,0,1,0,1] and [1,1,1]
Expected output: []

Input: ['t', 'a', 'n', 'z', 'a', 'n', 'i', 'a'] and ['a','n']
Expected output: [1, 4]
```

In [41]:
small = np.array([1,0,1])
large = np.array([0,0,1,1,0,1,1,0,1,0,1])

N = len(small)
M = len(large)

for i in range(M-N+1):
    if np.all(small==large[i:N+i]):
        print(i)

3
6
8


### nonzero where

In [44]:
x = np.array([4,0,-1,0,12,9])
x

array([ 4,  0, -1,  0, 12,  9])

In [45]:
indices = np.nonzero(x)
indices

(array([0, 2, 4, 5]),)

In [46]:
x[indices]

array([ 4, -1, 12,  9])

In [47]:
x < 5

array([ True,  True,  True,  True, False, False], dtype=bool)

In [48]:
np.nonzero(x < 5)

(array([0, 1, 2, 3]),)

In [49]:
x = np.arange(12).reshape(3,4)

In [50]:
rows, columns = np.where(x < 5)
print(rows)
print(columns)

[0 0 0 0 1]
[0 1 2 3 0]


In [51]:
x[rows, columns]

array([0, 1, 2, 3, 4])

In [52]:
ix = np.isin(x, [3, 4, 7])
print(ix)

[[False False False  True]
 [ True False False  True]
 [False False False False]]


In [53]:
np.where(ix)

(array([0, 1, 1]), array([3, 0, 3]))

In [54]:
np.where(x < 5, x, -1)  # Note: broadcasting.

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [55]:
np.where([[True, False], [True, True]],
          [[1, 2], [3, 4]],
          [[9, 8], [7, 6]])

array([[1, 8],
       [3, 4]])

#### Exercise
Create the array defined below and give all columns containing a number that is divisible to 9.

Input:
```python
array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])
```

Expected output:
```python
array([[ 0,  5,  4],
       [10, 15, 14],
       [20, 25, 24],
       [30, 35, 34],
       [40, 45, 44],
       [50, 55, 54]])
```

In [383]:
a = np.arange(6) + np.arange(0,51,10)[:, np.newaxis]
rows, columns = np.nonzero(a%9==0)

a[:,columns]

array([[ 0,  5,  4],
       [10, 15, 14],
       [20, 25, 24],
       [30, 35, 34],
       [40, 45, 44],
       [50, 55, 54]])

In [384]:
a = np.arange(6) + np.arange(0,51,10)[:, np.newaxis]
rows, columns = np.where(a%9==0)

a[:,columns]

array([[ 0,  5,  4],
       [10, 15, 14],
       [20, 25, 24],
       [30, 35, 34],
       [40, 45, 44],
       [50, 55, 54]])

### Aggregate Comparison

### sum max min sort

In [287]:
a = np.array([4, 3, 1, 2])
a

array([4, 3, 1, 2])

In [288]:
a.sum()

10

In [18]:
x = np.arange(12).reshape(3,4)

In [19]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
# row-wise
x.sum(axis=0)

array([12, 15, 18, 21])

In [21]:
# column-wise
x.sum(axis=1)

array([ 6, 22, 38])

In [22]:
x.prod()

0

In [23]:
x.prod(axis=0)

array([  0,  45, 120, 231])

In [391]:
x = np.array([1, 3, 2])

In [3]:
np.unique(np.array([1,2,2,3,4,5,2,3,4]))

array([1, 2, 3, 4, 5])

In [5]:
vals, counts = np.unique(np.array([1,2,2,3,4,5,2,3,4]), return_counts=True)
print(list(zip(vals, counts)))

[(1, 1), (2, 3), (3, 2), (4, 2), (5, 1)]


In [392]:
print(x.min())
print(x.argmin())

1
0


In [393]:
print(x.max())
print(x.argmax())

3
1


In [394]:
a = np.array([[4 , 2 , 5 ], [1 , 3 , 0 ]])
a

array([[4, 2, 5],
       [1, 3, 0]])

In [395]:
a.max(axis=0)

array([4, 3, 5])

In [396]:
a.min(axis=1)

array([2, 0])

In [397]:
np.sort?

In [398]:
a = np.array([[4 , 2 , 5 ], [1 , 3 , 0 ]])
a

array([[4, 2, 5],
       [1, 3, 0]])

In [399]:
np.sort(a, axis=0)

array([[1, 2, 0],
       [4, 3, 5]])

In [400]:
np.sort(a, axis=1)

array([[2, 4, 5],
       [0, 1, 3]])

In [401]:
a.sort(axis=0)
a

array([[1, 2, 0],
       [4, 3, 5]])

In [402]:
a = np.array([4, 3, 1, 2])
np.argsort(a)

array([2, 3, 1, 0])

In [403]:
people = np.array(['A', 'B', 'C', 'D'])
ages = np.array([32, 19, 24, 45])

indices = np.argsort(ages)
indices

array([1, 2, 0, 3])

In [404]:
people[indices]

array(['B', 'C', 'A', 'D'],
      dtype='<U1')

In [58]:
a = np.array([[4 , 2 , 5 ], 
              [1 , 3 , 0 ],
              [7 , 1 , 3 ],])
np.argsort(a, axis=0)

array([[1, 2, 1],
       [0, 0, 2],
       [2, 1, 0]])

In [59]:
a[np.argsort(a, axis=0)[:,0]]

array([[1, 3, 0],
       [4, 2, 5],
       [7, 1, 3]])

In [60]:
a

array([[4, 2, 5],
       [1, 3, 0],
       [7, 1, 3]])

In [64]:
np.argsort(a, axis=0)

array([[1, 2, 1],
       [0, 0, 2],
       [2, 1, 0]])

In [62]:
# indices = np.nonzero(np.argsort(a, axis=0))
indices = np.unravel_index(np.argsort(a, axis=0), a.shape)

print(len(indices))
print(indices[0])
print(indices[1])

2
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 2 1]
 [0 0 2]
 [2 1 0]]


In [63]:
indices

(array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]), array([[1, 2, 1],
        [0, 0, 2],
        [2, 1, 0]]))

In [65]:
np.unravel_index?

In [453]:
cols, rows = indices

In [454]:
a[rows[:,0],:]

array([[1, 3, 0],
       [4, 2, 5],
       [7, 1, 3]])

#### Exercise
Find total export in 10 years for each country.

Input:
```python
countries = np.array(['US','UK', 'Canada', 'Australia', 'Germany','Japan','Korea','India','Brazil', 'South Africa'])
# 1st dim: country, 2nd dim: year, 3rd dim: month
export_array = np.random.randint(10,100,100).reshape((10,10))
```

Expected output:
```python
[('US', 2008),
 ('UK', 2012),
 ('Canada', 2015),
 ('Australia', 2016),
 ('Germany', 2008),
 ('Japan', 2014),
 ('Korea', 2016),
 ('India', 2014),
 ('Brazil', 2014),
 ('South Africa', 2010)]
```

In [20]:
ncountry = 5
nyear = 10
nmonth = 12
export_array = np.random.randint(10,100,ncountry*nyear*nmonth).reshape((ncountry, nyear, nmonth))

In [22]:
country_year = np.sum(export_array, axis=2)
country_year

array([[514, 568, 663, 484, 612, 800, 588, 650, 643, 686],
       [649, 700, 719, 650, 695, 610, 565, 767, 614, 701],
       [704, 767, 573, 603, 557, 786, 628, 677, 565, 663],
       [595, 737, 746, 688, 673, 687, 615, 549, 715, 584],
       [835, 625, 704, 477, 540, 634, 509, 630, 576, 652]])

In [24]:
country_total = np.sum(country_year, axis=1)
country_total

array([6208, 6670, 6523, 6589, 6182])

#### Exercise
Find the year with maximum export in 10 years for each country.

Input:
```python
# row - year, column - country
years = np.arange(2007,2018)
countries = np.array(['US','UK', 'Canada', 'Australia', 'Germany','Japan','Korea','India','Brazil', 'South Africa'])
export_array = np.random.randint(10,100,100).reshape((10,10))
```

Expected output:
```python
[('US', 2008),
 ('UK', 2012),
 ('Canada', 2015),
 ('Australia', 2016),
 ('Germany', 2008),
 ('Japan', 2014),
 ('Korea', 2016),
 ('India', 2014),
 ('Brazil', 2014),
 ('South Africa', 2010)]
```

In [378]:
# row - year, column - country
years = np.arange(2007,2018)
countries = np.array(['US','UK', 'Canada', 'Australia', 'Germany','Japan','Korea','India','Brazil', 'South Africa'])
export_array = np.random.randint(10,100,100).reshape((10,10))

In [379]:
best_years = export_array.argmax(axis=0)
list(zip(countries, years[best_years]))

[('US', 2014),
 ('UK', 2012),
 ('Canada', 2016),
 ('Australia', 2012),
 ('Germany', 2009),
 ('Japan', 2010),
 ('Korea', 2012),
 ('India', 2014),
 ('Brazil', 2016),
 ('South Africa', 2009)]

## Matrix operations

In [32]:
large = np.array([0,0,1,1,0,1,1,0,1,0,1])
small = np.array([1,0,1])

N = len(large)
M = len(small)
for i in range(N):
    print(large[:M])
    print('-'*20)
    if np.all(small==large[:M]):
        print(i)
    large = np.roll(large, 1)

[0 0 1]
--------------------
[1 0 0]
--------------------
[0 1 0]
--------------------
[1 0 1]
--------------------
3
[0 1 0]
--------------------
[1 0 1]
--------------------
5
[1 1 0]
--------------------
[0 1 1]
--------------------
[1 0 1]
--------------------
8
[1 1 0]
--------------------
[0 1 1]
--------------------


In [37]:
a = np.array([[1, 2, 3], [3, 4, 5]])
b = np.array([1,1,1])

In [38]:
print('a', a.shape)
print('b', b.shape)

a (2, 3)
b (3,)


In [47]:
a.dot(b) # broadcast b to (3,1)

array([ 6, 12])

In [40]:
c = np.dot(a,b)
print(c)
print(c.shape)

array([ 6, 12])

In [42]:
np.dot(b,a)

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

In [50]:
print(a.T)
print(a.T.shape)

[[1 3]
 [2 4]
 [3 5]]
(3, 2)


In [49]:
d = np.dot(b,a.T) # broadcast b to (1,3)
print(d)
print(d.shape)

[ 6 12]
(2,)


In [41]:
a.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [53]:
a = np.array([1, 4, 0])
b = np.array([2, 2, 1])

In [54]:
np.dot(a,b)

10

In [55]:
np.dot(b,a)

10

In [56]:
np.inner(a,b)

10

In [57]:
np.outer(a,b) # both arrays broadcasted up

array([[2, 2, 1],
       [8, 8, 4],
       [0, 0, 0]])

#### Exercise
Find each person's age ratio to other people.

```python
ages = np.array([30,25,42,19, 13, 27])
```

In [49]:
ages = np.array([30,25,42,19, 13, 27])
iprint(np.outer(ages, 1/ages), sep='-'*80)

[ 1.          1.2         0.71428571  1.57894737  2.30769231  1.11111111]
--------------------------------------------------------------------------------
[ 0.83333333  1.          0.5952381   1.31578947  1.92307692  0.92592593]
--------------------------------------------------------------------------------
[ 1.4         1.68        1.          2.21052632  3.23076923  1.55555556]
--------------------------------------------------------------------------------
[ 0.63333333  0.76        0.45238095  1.          1.46153846  0.7037037 ]
--------------------------------------------------------------------------------
[ 0.43333333  0.52        0.30952381  0.68421053  1.          0.48148148]
--------------------------------------------------------------------------------
[ 0.9         1.08        0.64285714  1.42105263  2.07692308  1.        ]
--------------------------------------------------------------------------------


In [257]:
a.conj()

array([[1, 2, 3],
       [3, 4, 5]])

In [263]:
x = np.eye(2) + 1j * np.eye(2)
x

array([[ 1.+1.j,  0.+0.j],
       [ 0.+0.j,  1.+1.j]])

In [264]:
np.conjugate(x)

array([[ 1.-1.j,  0.-0.j],
       [ 0.-0.j,  1.-1.j]])

In [61]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [62]:
np.linalg.det(x)

-2.0000000000000004

In [63]:
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [66]:
vals, vecs = np.linalg.eig(x)
print('Eigenvalues:\n', vals)
print('Eigenvectors:\n', vecs)

Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [72]:
U, s, Vh = np.linalg.svd(x)

In [71]:
print('U:\n', U)
print('s:\n', s)
print('Vh:\n', Vh)

U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
s:
 [ 5.4649857   0.36596619]
Vh:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [69]:
s

array([ 5.4649857 ,  0.36596619])

In [70]:
Vh

array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]])

#### Exercise
Solve following equations.

```
x + 2y = 1
3x + 4y = 10
```


In [327]:
m = np.array([[1,2],[3,4]])
n = np.array([1,10])

In [328]:
np.linalg.inv(m)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [329]:
np.linalg.inv(m).dot(n)

array([ 8. , -3.5])