# Numpy

In [1]:
import numpy as np

## Broadcasting

<img src='../img/numpy_broadcasting.png'>

In [2]:
b = np.array([0, 1, 2])

In [3]:
b

array([0, 1, 2])

In [10]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [11]:
a

array([ 0, 10, 20, 30])

In [12]:
a + b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [13]:
a = a[:, np. newaxis] # adds a new axis -> 2D array
a.shape

(4, 1)

In [14]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [15]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### Mesh

In [21]:
x, y = np.ogrid[ 0:5 , 0:5 ]
print(x, x.shape)
print()
print(y, y.shape)

[[0]
 [1]
 [2]
 [3]
 [4]] (5, 1)

[[0 1 2 3 4]] (1, 5)


In [22]:
np.sqrt(x**2 + y**2)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.41421356,  2.23606798,  3.16227766,  4.12310563],
       [ 2.        ,  2.23606798,  2.82842712,  3.60555128,  4.47213595],
       [ 3.        ,  3.16227766,  3.60555128,  4.24264069,  5.        ],
       [ 4.        ,  4.12310563,  4.47213595,  5.        ,  5.65685425]])

In [30]:
x, y = np.mgrid[0:3, 10:40:10]

In [31]:
x

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [32]:
y

array([[10, 20, 30],
       [10, 20, 30],
       [10, 20, 30]])

In [33]:
np.sqrt(x**2 + y**2)

array([[ 10.        ,  20.        ,  30.        ],
       [ 10.04987562,  20.02498439,  30.01666204],
       [ 10.19803903,  20.09975124,  30.06659276]])

In [41]:
aa, bb, cc = np.ogrid[0:1:2j, 0:1:5j, 0:1:3j]

In [42]:
aa, bb, cc

(array([[[ 0.]],
 
        [[ 1.]]]), array([[[ 0.  ],
         [ 0.25],
         [ 0.5 ],
         [ 0.75],
         [ 1.  ]]]), array([[[ 0. ,  0.5,  1. ]]]))

## Array manipulation

### tile

In [46]:
np.tile?

In [43]:
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [44]:
np.tile(a, (2,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2]])

### repeat

In [45]:
np.repeat?

In [ ]:
np.repeat(3, 4)

In [47]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [48]:
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [49]:
np.repeat(x, 3, axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [50]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [51]:
# specify repeat count for each element
np.repeat(x, (3,2), axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

### concatenate

In [52]:
np.concatenate((np.arange(3),np.arange(3)), axis=0)

array([0, 1, 2, 0, 1, 2])

In [53]:
np.concatenate((np.arange(3),np.arange(3)), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [54]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
b = np.arange(4).reshape(1,4)
b

array([[0, 1, 2, 3]])

In [56]:
np.concatenate((a,b), axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [61]:
c = np.arange(3).reshape(3,1)
c

array([[0],
       [1],
       [2]])

In [62]:
np.concatenate((a,c), axis=1)

array([[ 0,  1,  2,  3,  0],
       [ 4,  5,  6,  7,  1],
       [ 8,  9, 10, 11,  2]])

### append

In [ ]:
np.append?

In [ ]:
a = np.arange(5)
a

In [ ]:
np.append(a, [5])

In [ ]:
np.append(a, [5,6])

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

In [ ]:
np.append(x, [7, 8, 9])

In [ ]:
np.append(x, [[7, 8, 9]])

In [ ]:
x

In [ ]:
np.append(x, [[7, 8, 9]], axis=0)

In [ ]:
np.append(x, [7, 8, 9], axis=0)

In [ ]:
np.append([[1, 2, 3]], [[7, 8, 9]], axis=1)

### hstack vstack

In [ ]:
def iprint(seq, sep='--------'):
    for item in seq:
        print(item)
        print(sep)

In [ ]:
iprint([1,2,3])

In [ ]:
arrays = [np.random.randint(0,10, (2, 3)) for i in range(3)]

In [ ]:
iprint(arrays)

In [ ]:
h = np.hstack(arrays)
h

In [ ]:
h.shape

In [ ]:
v = np.vstack(arrays)
v

In [ ]:
v.shape

In [ ]:
b = np.arange(6)

for i in range(5):
    start = (i+1)*10
    end = start + 6
    c = np.arange(start, end)
    b = np.vstack((b,c))

In [ ]:
b

### stack

In [ ]:
arrays = [np.random.randint(0,10, (2, 4)) for i in range(3)]

In [ ]:
iprint(arrays)

In [ ]:
s0 = np.stack(arrays, axis=0)
s0

In [ ]:
s0.shape

In [ ]:
s1 = np.stack(arrays, axis=1)
s1

In [ ]:
s1.shape

In [ ]:
s2 = np.stack(arrays, axis=2)
s2

In [ ]:
s2.shape

In [ ]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

In [ ]:
np.stack((a,b), axis=1)

### split

In [ ]:
np.split?

In [ ]:
x = np.arange(9)
np.split(x, 3)

In [ ]:
x = np.arange(8)
np.split(x, [3, 5, 6, 10])

### array_split

For an array of length L that should be split into n sections, it returns L % n sub-arrays of size L//n + 1 and the rest of size L//n.

In [ ]:
np.split(np.arange(9), 4)

In [ ]:
np.array_split(np.arange(9), 4)

### hsplit vsplit

In [ ]:
x = np.arange(24).reshape(6, 4)
x

In [ ]:
iprint(np.hsplit(x, 2))

In [ ]:
iprint(np.hsplit(x, np.array([3, 6])))

In [ ]:
iprint(np.vsplit(x, 2))

In [ ]:
iprint(np.vsplit(x, np.array([2, 4])))

## IO

#### Byte file

In [ ]:
x = np.arange(100).reshape((10,10))

In [ ]:
np.save?

In [ ]:
np.save('./data/x.npy', x)

In [ ]:
y = np.load('./data/x.npy')

In [ ]:
y

In [ ]:
np.all(x==y)

#### Text file

In [ ]:
x = np.arange(100).reshape((10,10))

In [ ]:
np.savetxt('./data/x.txt', x)

In [ ]:
y = np.loadtxt('./data/x.txt')

In [ ]:
np.all(x==y)

In [ ]:
np.savetxt('./data/array2D.csv', x, fmt='%.6f', delimiter=';')

In [ ]:
np.loadtxt('./data/array2D.csv',delimiter=';')

## Advanced Operations

#### Vectorize

In [63]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b

In [64]:
vfunc = np.vectorize(myfunc)

In [65]:
vfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])

In [66]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [67]:
vfunc(a, 2)

array([[2, 3],
       [4, 1],
       [2, 3]])

In [68]:
vfunc(2, [1, 2, 3, 4])

array([1, 4, 5, 6])

In [69]:
vfunc([1, 2, 3, 4], [1, 2, 3, 4])

array([2, 4, 6, 8])

#### Apply along axis

In [ ]:
np.apply_along_axis?

In [ ]:
def my_func(a):
    """Average first and last element of a 1-D array"""
    return (a[0] + a[-1]) * 0.5

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

In [ ]:
np.apply_along_axis(my_func, axis=0, arr=a)

In [ ]:
np.apply_along_axis(my_func, axis=1, arr=a)

In [ ]:
np.apply_along_axis?

#### Apply along axis

In [ ]:
np.apply_over_axes?

In [ ]:
a = np.arange(24).reshape(2,3,4)

In [ ]:
a.shape

In [ ]:
b = np.apply_over_axes(np.sum, a, [0,2])
b

In [ ]:
b.shape

In [ ]:
np.sum(a, axis=(0,2), keepdims=True)

### Structured data types

In [ ]:
a = np.arange(24).reshape(2,3,4)
a

In [ ]:
a[0,...]

In [ ]:
a[:,:,0]

In [ ]:
samples = np.zeros((6,), dtype= [('sensor_code', 'S4'),
                                 ('position', float), 
                                 ('value', float)])

In [ ]:
print samples.ndim
print samples.shape
print samples.dtype.names

In [ ]:
samples[:] = [('ALFA', 1, 0.37), 
              ('BETA', 1, 0.11),
              ('TAU', 1, 0.13),
              ('ALFA', 1.5, 0.37),
              ('ALFA', 3, 0.11),
              ('TAU', 1.2, 0.13)]

In [ ]:
samples

In [ ]:
samples['sensor_code']

In [ ]:
samples['value']

In [ ]:
samples[ 0 ]

### Masked arrays

In [ ]:
x = np.ma.array([1 , 2 , 3 , 4 ], mask= [ 0 , 1 , 0 , 1 ])
x

In [ ]:
np.ma.sqrt([ 1 , - 1 , 2 , - 2 ])

### Polynomials

In [ ]:
p = np.poly1d([3 , 2 , - 1 ])
p(0)

In [ ]:
p.roots

In [ ]:
print(p.coeffs)
print(p.order)

In [ ]:
x = np.linspace(- 1 , 1 , 2000)
y = np.cos(x) + 0.3 * np.random.rand(2000)
p = np.polynomial.Chebyshev.fit(x, y, 90)

In [ ]:
p.degree()

### Exercises

#### Mesh and vectorize

In [ ]:
frequency = np.arange(1,6)

In [ ]:
ratioMesh = np.outer(frequency, 1.0 / frequency)
ratioMesh

In [ ]:
zeta = 0.05

In [ ]:
transmissibility = lambda r: (abs((1 + 1j * 2 * zeta * r) / (1 - r ** 2 + 1j * 2 * zeta * r)))

In [ ]:
transmissibility(0.5)

In [ ]:
transmissibility_vec = np.vectorize(TR)

In [ ]:
transmissibility_vec(ratioMesh)

#### Simple dataset operations

In [ ]:
data = np.loadtxt('data/populations.txt')
year, hares, lynxes, carrots = data.T # trick: columns to variables

In [ ]:
data

In [ ]:
plt.axes([0.2 , 0.1 , 0.5 , 0.8 ])
plt.plot(year, hares, year, lynxes, year, carrots)
plt.legend(('Hare ', 'Lynx' , ' Carrot'), loc = ( 1.05, 0.5))

In [ ]:
populations = data[:, 1 :]
populations.mean(axis=0)

In [ ]:
populations.std(axis=0)

In [ ]:
np.argmax(populations, axis=1)

#### Distance

In [ ]:
a = np.random.rand(30).reshape((10,3))

In [ ]:
inds = np.argsort(np.abs(a-0.5))

In [ ]:
a[range(10), inds[:,0]]

#### Simple image operations

In [ ]:
from scipy import misc
face = misc.face(gray=True) # 2D grayscale image

In [ ]:
plt.imshow(face, cmap=plt.cm.gray)

In [ ]:
sy, sx = face.shape
y, x = np.ogrid[0:sy, 0:sx] # x and y indices of pixels

centerx, centery = ( 660 , 300 ) # center of the image
mask = ((y - centery)**2 + (x - centerx)**2 ) > 200**2 # circle

In [ ]:
face[mask] = 0
plt.imshow(face, cmap=plt.cm.gray)