# Numpy

In [2]:
import numpy as np

In [3]:
def iprint(seq, sep='--------'):
    for item in seq:
        print(item)
        print(sep)

# Array Manipulation

## Constructing

### tile

In [18]:
np.tile?

In [19]:
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [20]:
np.tile(a, (2,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2]])

### repeat

In [21]:
np.repeat?

In [22]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [23]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [24]:
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [25]:
np.repeat(x, 3, axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [26]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [27]:
# specify repeat count for each element
np.repeat(x, (3,2), axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

### concatenate

In [28]:
np.concatenate((np.arange(3),np.arange(3)), axis=0)

array([0, 1, 2, 0, 1, 2])

In [29]:
np.concatenate((np.arange(3),np.arange(3)), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [4]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
b = np.arange(4).reshape(1,4)
b

array([[0, 1, 2, 3]])

In [6]:
np.concatenate((a,b), axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [33]:
c = np.arange(3).reshape(3,1)
c

array([[0],
       [1],
       [2]])

In [34]:
np.concatenate((a,c), axis=1)

array([[ 0,  1,  2,  3,  0],
       [ 4,  5,  6,  7,  1],
       [ 8,  9, 10, 11,  2]])

### append

In [35]:
np.append?

In [36]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [37]:
np.append(a, [5])

array([0, 1, 2, 3, 4, 5])

In [38]:
np.append(a, [5,6])

array([0, 1, 2, 3, 4, 5, 6])

In [39]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.append(x, [7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.append(x, [[7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.append(x, [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
np.append(x, [7, 8, 9], axis=0)

ValueError: all the input arrays must have same number of dimensions

In [45]:
np.append([[1, 2, 3]], [[7, 8, 9]], axis=1)

array([[1, 2, 3, 7, 8, 9]])

### stack

In [56]:
arrays = [np.random.randint(0,10, (2, 4)) for i in range(3)]

In [57]:
iprint(arrays)

[[8 1 5 3]
 [9 2 1 1]]
--------
[[9 6 3 7]
 [5 2 9 6]]
--------
[[5 8 3 4]
 [7 7 0 1]]
--------


In [58]:
s0 = np.stack(arrays, axis=0)
s0

array([[[8, 1, 5, 3],
        [9, 2, 1, 1]],

       [[9, 6, 3, 7],
        [5, 2, 9, 6]],

       [[5, 8, 3, 4],
        [7, 7, 0, 1]]])

In [59]:
s0.shape

(3, 2, 4)

In [60]:
s1 = np.stack(arrays, axis=1)
s1

array([[[8, 1, 5, 3],
        [9, 6, 3, 7],
        [5, 8, 3, 4]],

       [[9, 2, 1, 1],
        [5, 2, 9, 6],
        [7, 7, 0, 1]]])

In [61]:
s1.shape

(2, 3, 4)

In [62]:
s2 = np.stack(arrays, axis=2)
s2

array([[[8, 9, 5],
        [1, 6, 8],
        [5, 3, 3],
        [3, 7, 4]],

       [[9, 5, 7],
        [2, 2, 7],
        [1, 9, 0],
        [1, 6, 1]]])

In [63]:
s2.shape

(2, 4, 3)

In [20]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [65]:
np.stack((a,b), axis=1)

array([[1, 2],
       [2, 3],
       [3, 4]])

### hstack vstack

In [47]:
iprint([1,2,3])

1
--------
2
--------
3
--------


In [48]:
arrays = [np.random.randint(0,10, (2, 3)) for i in range(3)]

In [49]:
iprint(arrays)

[[2 0 8]
 [4 3 3]]
--------
[[3 0 2]
 [3 1 4]]
--------
[[7 0 4]
 [8 6 3]]
--------


In [50]:
h = np.hstack(arrays)
h

array([[2, 0, 8, 3, 0, 2, 7, 0, 4],
       [4, 3, 3, 3, 1, 4, 8, 6, 3]])

In [51]:
h.shape

(2, 9)

In [52]:
v = np.vstack(arrays)
v

array([[2, 0, 8],
       [4, 3, 3],
       [3, 0, 2],
       [3, 1, 4],
       [7, 0, 4],
       [8, 6, 3]])

In [53]:
v.shape

(6, 3)

In [54]:
b = np.arange(6)

for i in range(5):
    start = (i+1)*10
    end = start + 6
    c = np.arange(start, end)
    b = np.vstack((b,c))

In [55]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

#### Exercise
Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]]

In [4]:
x = np.array([1,2,3])
y = np.array([4,5,6])

z = np.vstack([x,y]).T
z

array([[1, 4],
       [2, 5],
       [3, 6]])

## Deconstructing

### split

In [19]:
np.split?

In [67]:
x = np.arange(9)
np.split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [68]:
x = np.arange(8)
np.split(x, [3, 5, 6, 10])

[array([0, 1, 2]),
 array([3, 4]),
 array([5]),
 array([6, 7]),
 array([], dtype=int64)]

### array_split

For an array of length L that should be split into n sections, it returns L % n sub-arrays of size L//n + 1 and the rest of size L//n.

In [69]:
np.split(np.arange(9), 4)

ValueError: array split does not result in an equal division

In [70]:
np.array_split(np.arange(9), 4)

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

### hsplit vsplit

In [71]:
x = np.arange(24).reshape(6, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [72]:
iprint(np.hsplit(x, 2))

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]]
--------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]]
--------


In [73]:
iprint(np.hsplit(x, np.array([3, 6])))

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]
 [20 21 22]]
--------
[[ 3]
 [ 7]
 [11]
 [15]
 [19]
 [23]]
--------
[]
--------


In [74]:
iprint(np.vsplit(x, 2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------


In [75]:
iprint(np.vsplit(x, np.array([2, 4])))

[[0 1 2 3]
 [4 5 6 7]]
--------
[[ 8  9 10 11]
 [12 13 14 15]]
--------
[[16 17 18 19]
 [20 21 22 23]]
--------


#### Exercise
Create the array below with hsplit.

```python
array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])
```

In [18]:
np.hsplit(np.arange(60).reshape((6,-1)), [6])[0]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

#### Exercise
Let x be an array 
```
[[ 0., 1., 2., 3.],
[ 4., 5., 6., 7.],
[ 8., 9., 10., 11.],
[ 12., 13., 14., 15.]]
```
Split it into two arrays along the second axis.

In [8]:
a = np.arange(16).reshape(4,4)
iprint(np.hsplit(a, 2))

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
--------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
--------


## Moving

In [8]:
x = np.arange(0, 12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.roll?

In [10]:
np.roll(x,1) # flat shifting

array([[11,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [13]:
np.roll(x, 1, axis=0) # shift along row

array([[ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [14]:
np.roll(x, 1, axis=1) # shift along column

array([[ 3,  0,  1,  2],
       [ 7,  4,  5,  6],
       [11,  8,  9, 10]])

In [15]:
x = np.array([[1,2], [3,4]])
np.rot90(x)

array([[2, 4],
       [1, 3]])